@host = http://localhost:3000
@urlUsers = /api/users
@urlSlots = /api/timeslots


#### USERS GET

GET {{host}}{{urlUsers}}

### USERS REGISTER

POST {{host}}{{urlUsers}}/signup
Content-Type: application/json

{
    "Name": "Fran",
    "Surname": "Ortega",
    "Phone": "678XXXXX",
    "Email": "test@mail.es",
    "Password": "1234"
}

### USERS LOGIN
POST {{host}}{{urlUsers}}/signin
Content-Type: application/json

{
    "Email": "test@mail.es",
    "Password": "1234"
}

### TIMESLOTS
GET {{host}}{{urlSlots}}/slots
Content-Type: application/json

{
    "ReservationDate": "2024-11-08"
}